'use client';
import {useEffect,useState} from 'react';
import {ChevronLeft,ChevronRight,MapPin,ArrowUpRight,CalendarDays} from 'lucide-react';
import {Sheet,SheetContent,SheetTitle,SheetDescription} from '@/components/ui/sheet';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import courses from './courses.json';
import {occurrences,addDays,monday,time,type Course,type Meeting} from './schedule';
const palette=['blue','violet','orange','teal','pink','indigo','red','green','cyan'];
const codes=[...new Set(courses.map(c=>c.code))];
const tone=(c:Course)=>palette[codes.indexOf(c.code)];
const pretty=(d:string,opts:Intl.DateTimeFormatOptions)=>new Date(d+'T12:00:00').toLocaleDateString('en-CA',opts);
const shortPlace=(m:Meeting)=>m.pattern.building?`${m.pattern.building.match(/\(([^()]*)\)$/)?.[1]||m.pattern.building} ${m.rooms.join(' / ')}`:'Location not listed';
export default function Home(){
 const [term,setTerm]=useState(1),[date,setDate]=useState('2026-09-08'),[view,setView]=useState('week'),[selected,setSelected]=useState<Meeting|null>(null);
 useEffect(()=>{const today=new Intl.DateTimeFormat('en-CA',{timeZone:'America/Vancouver',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());if(today>='2026-09-08'&&today<='2027-04-12'){setDate(today);setTerm(today<'2027-01-01'?1:2)}},[]);
 const termCourses=courses.filter(c=>c.term===term),week=monday(date),days=Array.from({length:5},(_,i)=>addDays(week,i));
 const unique=termCourses.filter((c,i,a)=>a.findIndex(x=>x.code===c.code)===i);
 function changeTerm(t:number){setTerm(t);setDate(t===1?'2026-09-08':'2027-01-05')}
 function calendar(dayView:boolean){const shown=dayView?[date]:days;return <div className={`calendar-scroll ${dayView?'single-day':''}`}><div className="calendar" style={{gridTemplateColumns:`54px repeat(${shown.length},minmax(${dayView?'0':'146'}px,1fr))`}}><div className="corner">PDT/PST</div>{shown.map(d=><button className={`column-head ${d===date?'picked':''}`} key={d} onClick={()=>{setDate(d);setView('day')}}><span>{pretty(d,{weekday:'short'})}</span><strong>{pretty(d,{day:'numeric'})}</strong></button>)}<div className="hour-labels">{Array.from({length:10},(_,i)=><span key={i} style={{top:i*84}}>{i+9>12?i-3:i+9}<small>{i+9<12?'AM':'PM'}</small></span>)}</div>{shown.map(d=><div className="day-column" key={d}>{Array.from({length:10},(_,i)=><div className="hour-line" key={i} style={{top:i*84}}/>)}{occurrences(d,term).map(m=><button className={`event ${tone(m.course)}`} key={m.key} style={{top:(m.pattern.fromMin-540)*1.4,height:(m.pattern.toMin-m.pattern.fromMin)*1.4-3}} onClick={()=>setSelected(m)} aria-label={`${m.course.code}, ${m.course.kind}, ${time(m.pattern.fromMin)} to ${time(m.pattern.toMin)}, ${shortPlace(m)}`}><strong>{m.course.code}</strong><span className="event-kind">{m.course.kind==='Laboratory'?'Lab':m.course.kind==='Discussion'?'Disc.':'Lec.'}{m.pattern.alternate?' · A/W':''}</span><span className="event-time">{time(m.pattern.fromMin)} – {time(m.pattern.toMin)}</span><span className="event-room">{shortPlace(m)}</span></button>)}{!occurrences(d,term).length&&<span className="no-classes">No classes</span>}</div>)}</div></div>}
 return <main className="app"><header className="masthead"><div className="brand-icon"><CalendarDays size={24}/></div><div><p className="eyebrow">UBC VANCOUVER · 2026–27</p><h1>My courses<span>.</span></h1></div><span className="campus-label">Your week, at a glance</span></header><div className="term-row"><div className="term-switch" aria-label="Academic term">{[1,2].map(t=><button key={t} aria-pressed={term===t} className={term===t?'active':''} onClick={()=>changeTerm(t)}>Term {t}<span>{t===1?'Sep – Dec':'Jan – Apr'}</span></button>)}</div><p>{unique.length} courses <span>·</span> {unique.reduce((s,c)=>s+c.credits,0)} credits</p></div>
 <Tabs value={view} onValueChange={v=>setView(String(v))}><div className="toolbar"><TabsList className="view-tabs"><TabsTrigger value="day">Day</TabsTrigger><TabsTrigger value="week">Week</TabsTrigger><TabsTrigger value="courses">Courses</TabsTrigger></TabsList>{view!=='courses'&&<div className="date-nav"><button aria-label="Previous" onClick={()=>setDate(addDays(date,view==='week'?-7:-1))}><ChevronLeft size={20}/></button><label><span className="sr-only">Choose date</span><input type="date" value={date} onChange={e=>{if(e.target.value){setDate(e.target.value);setTerm(e.target.value<'2027-01-01'?1:2)}}}/></label><button aria-label="Next" onClick={()=>setDate(addDays(date,view==='week'?7:1))}><ChevronRight size={20}/></button></div>}</div><div className="calendar-heading"><h2>{view==='courses'?'All your courses':view==='day'?pretty(date,{weekday:'long',month:'short',day:'numeric'}):`${pretty(week,{month:'long',day:'numeric'})} – ${pretty(addDays(week,4),{month:'short',day:'numeric'})}`}</h2>{view==='week'&&<span className="scroll-hint">Tap a class for details</span>}</div>
 <div className="legend">{unique.map(c=><span className={tone(c)} key={c.code}><i/>{c.code}</span>)}</div>
 <TabsContent value="day">{calendar(true)}</TabsContent><TabsContent value="week">{calendar(false)}</TabsContent><TabsContent value="courses"><div className="course-grid">{unique.map(c=><section className={`course-summary ${tone(c)}`} key={c.code}><strong>{c.code}</strong><h3>{c.title}</h3><p>{c.credits} credits</p>{termCourses.filter(s=>s.code===c.code).map(s=><button key={s.id} onClick={()=>setSelected({key:String(s.id),course:s,pattern:s.patterns[0],rooms:[...new Set(s.patterns.map(p=>p.room).filter(Boolean))],date:s.patterns[0].start})}><span>{s.kind}</span><span>{s.section.split('-').slice(1).join('-')} <ChevronRight size={16}/></span></button>)}</section>)}</div></TabsContent></Tabs>
 <footer><p>Vancouver time · A/W = alternate weeks · Tap a class for details and maps.</p><p>From your course export. Alternate weeks are counted from each listed meeting start date; confirm with your instructor. Holidays and changes not in the export are not applied.</p></footer>
 <Sheet open={!!selected} onOpenChange={open=>{if(!open)setSelected(null)}}><SheetContent side="bottom" className="details-sheet">{selected&&<><div className={`detail-color ${tone(selected.course)}`}/><p className="eyebrow">{selected.course.kind} · {selected.course.section}</p><SheetTitle className="detail-code">{selected.course.code}</SheetTitle><SheetDescription className="detail-title">{selected.course.title}</SheetDescription><div className="detail-time">{time(selected.pattern.fromMin)} – {time(selected.pattern.toMin)}</div><div className="detail-location"><MapPin size={23}/><div><strong>{selected.pattern.building||'Location not listed'}</strong><p>{selected.pattern.building?`Room ${selected.rooms.join(' / ')} · Floor ${selected.pattern.floor}`:'Check your course page for the room or online link.'}</p>{selected.rooms.length>1&&<p>Both rooms are listed in your export.</p>}</div></div>{selected.pattern.building&&<div className="map-actions"><a href={`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(selected.pattern.building+' UBC Vancouver')}`} target="_blank" rel="noopener noreferrer">Google Maps <ArrowUpRight size={18}/></a><a href={`https://maps.apple.com/?q=${encodeURIComponent(selected.pattern.building+' UBC Vancouver')}`} target="_blank" rel="noopener noreferrer">Apple Maps <ArrowUpRight size={18}/></a></div>}<dl><div><dt>Instructor</dt><dd>{selected.course.instructor}</dd></div><div><dt>Delivery</dt><dd>{selected.course.delivery}</dd></div></dl><h3 className="meeting-label">Meeting schedule</h3>{selected.course.patterns.filter((p,i,a)=>a.findIndex(x=>x.start===p.start&&x.end===p.end&&x.fromMin===p.fromMin)===i).map((p,i)=><p className="meeting-line" key={i}>{p.days.map(d=>['Mon','Tue','Wed','Thu','Fri','Sat','Sun'][d]).join(', ')}{p.alternate?' · Alternate weeks':''}<br/>{pretty(p.start,{month:'short',day:'numeric',year:'numeric'})} – {pretty(p.end,{month:'short',day:'numeric',year:'numeric'})}</p>)}</>}</SheetContent></Sheet></main>
}

